version: '3.7'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    hostname: elasticsearch
    volumes:
      - ./docker/elasticsearch/data:/usr/share/elasticsearch/data
      - ./docker/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    hostname: kibana
    volumes:
      - ./docker/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"

#  zookeeper:
#    image: strimzi/kafka:0.11.3-kafka-2.1.0
#    command: [
#      "sh", "-c",
#      "bin/zookeeper-server-start.sh config/zookeeper.properties"
#    ]
#    ports:
#      - "2181:2181"
#    environment:
#      LOG_DIR: /tmp/logs
#
#  kafka:
#    image: strimzi/kafka:0.11.3-kafka-2.1.0
#    container_name: kafka
#    hostname: kafka
#    command: [
#      "sh", "-c",
#      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
#    ]
#    depends_on:
#      - zookeeper
#    ports:
#      - "9092:9092"
#    environment:
#      LOG_DIR: "/tmp/logs"
#      #      KAFKA_ADVERTISED_HOST_NAME: kafka
#      #      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
#      #      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
#      #      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9092
#      #      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      #      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
#      KAFKA_ADVERTISED_HOST_NAME: kafka
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

#  wiremock:
#    image: rodolpheche/wiremock
#    ports:
#    - "8123:8080"